language: node_js
node_js:
  - "lts/*"

install:
  - yarn

script:
  - yarn build

after_success:
  - echo $TRAVIS_BRANCH
  - if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ]; then GITHUB_TOKEN=$GITHUB_TOKEN ./deploy.sh; fi
