language: node_js
node_js:
  - "lts/*"

install:
  - npm i -g hexo-cli
  - npm i

script:
  - hexo g

after_success:
  - repo=https://$GITHUB_TOKEN@github.com/ac-voyage/ac-voyage.github.io.git
  - sed -i "s/git@github.com:ac-voyage\/ac-voyage.github.io.git/$repo/g" _config.yml
  - git clone $repo .deploy_git
  - hexo d
